name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Bump version
        env:
          REF: ${{ github.ref }}
        run: |
          sed -i "s/apiVersion=SNAPSHOT/apiVersion=${REF:11}/" gradle.properties
      - name: Create release with Gradle
        run: ./gradlew clean build -x test

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            application/build/libs/*.jar

      - name: Publish Npm Package
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mineaurion'
      - run: npm publish
        working-directory: ./application/build/typescript-generator
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Gradle Package
        run: ./gradlew :library:build -x test :library:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

